version: "3.8"

services:
  controller:
    build:
      context: containers/controller
    image: silvasonic-controller:latest
    container_name: silvasonic_controller
    privileged: true # To spawn privileged siblings and access Host hardware info
    environment:
      # Pass Host paths so Controller can map them into Child Recorders
      - HOST_SILVASONIC_DATA_DIR=${SILVASONIC_DATA_DIR}
      # - HOST_RECORDER_SRC=./containers/recorder/src  # Optional: For dev hot-reload in siblings
    volumes:
      # 1. Podman Socket (Orchestration)
      - ${PODMAN_SOCKET}:/run/podman/podman.sock:z
      # 2. Hardware Discovery
      - /dev:/dev:ro
      - /run/udev:/run/udev:ro
      # 3. Source Code (Deployment)
      - ./containers/recorder/mic_profiles:/app/mic_profiles:ro
      # 4. Logs
      - ${SILVASONIC_DATA_DIR}/logs:/var/log/silvasonic:z
    restart: always

  uploader:
    build:
      context: containers/uploader
    image: silvasonic-uploader:latest
    container_name: silvasonic_uploader
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./containers/uploader/src:/app/src:z
      - ${SILVASONIC_DATA_DIR}/recorder/recordings:/data/recording:ro
      - ${SILVASONIC_DATA_DIR}/uploader/config:/config/rclone:z
      - ${SILVASONIC_DATA_DIR}/logs:/var/log/silvasonic:z
      - ${SILVASONIC_DATA_DIR}/status:/mnt/data/services/silvasonic/status:z
      - ${SILVASONIC_DATA_DIR}/errors:/mnt/data/services/silvasonic/errors:z
    restart: always

  healthchecker:
    build:
      context: containers/healthchecker
    image: silvasonic-healthchecker:latest
    container_name: silvasonic_healthchecker
    restart: always
    env_file: .env
    volumes:
      - ./containers/healthchecker/src:/app/src:z
      - ${SILVASONIC_DATA_DIR}/config:/config:z
      - ${SILVASONIC_DATA_DIR}/status:/mnt/data/services/silvasonic/status:z
      - ${SILVASONIC_DATA_DIR}/errors:/mnt/data/services/silvasonic/errors:z
      - ${SILVASONIC_DATA_DIR}/notifications:/data/notifications:z
      - ${SILVASONIC_DATA_DIR}/logs:/var/log/silvasonic:z

  birdnet:
    build:
      context: containers/birdnet
    image: silvasonic-birdnet:latest
    container_name: silvasonic_birdnet
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_DIR=/data/recording
      - RESULTS_DIR=/data/results
      - MIN_CONFIDENCE=0.7
      - RECURSIVE_WATCH=true
    volumes:
      - ./containers/birdnet/src:/app/src:z
      - ${SILVASONIC_DATA_DIR}/recorder/recordings:/data/recording:ro
      - ${SILVASONIC_DATA_DIR}/config:/config:ro
      - ${SILVASONIC_DATA_DIR}/birdnet/results:/data/results:z
      - ${SILVASONIC_DATA_DIR}/logs:/var/log/silvasonic:z
      - ${SILVASONIC_DATA_DIR}/status:/mnt/data/services/silvasonic/status:z
      - ${SILVASONIC_DATA_DIR}/notifications:/data/notifications:z
    restart: always

  recorder:
    build:
      context: containers/recorder
    image: silvasonic-recorder:latest
    container_name: silvasonic_recorder_template
    # Template container: Stopped by default, used as image source or dev base
    entrypoint: ["/bin/true"]
    restart: "no"
    volumes:
      - ./containers/recorder/src:/app/src:z
      - ./containers/recorder/mic_profiles:/app/mic_profiles:ro
      - ${SILVASONIC_DATA_DIR}/recorder/recordings:/data/recording:z
      - ${SILVASONIC_DATA_DIR}/logs:/var/log/silvasonic:z

  livesound:
    build:
      context: containers/livesound
    image: silvasonic-livesound:latest
    container_name: silvasonic_livesound
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
      - "1234:1234/udp"
    cpu_shares: 512
    volumes:
      - ./containers/livesound/src:/app/src:z
      - ${SILVASONIC_DATA_DIR}/recorder/recordings:/data/recording:ro
      - ${SILVASONIC_DATA_DIR}/logs:/var/log/silvasonic:z
      - ${SILVASONIC_DATA_DIR}/status:/mnt/data/services/silvasonic/status:z
    restart: always

  dashboard:
    build:
      context: containers/dashboard
    image: silvasonic-dashboard:latest
    container_name: silvasonic_dashboard
    hostname: silvasonic-dashboard
    restart: always
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"
    volumes:
      - ./containers/dashboard/src:/app/src:z
      - ${SILVASONIC_DATA_DIR}/recorder/recordings:/data/recording:ro
      - ${SILVASONIC_DATA_DIR}/config:/config:z
      - ${SILVASONIC_DATA_DIR}/logs:/var/log/silvasonic:z
      - ${SILVASONIC_DATA_DIR}/status:/mnt/data/services/silvasonic/status:z

  weather:
    build:
      context: containers/weather
    image: silvasonic-weather:latest
    container_name: silvasonic_weather
    restart: always
    env_file: .env
    volumes:
      - ./containers/weather/src:/app/src:z
      - ${SILVASONIC_DATA_DIR}/config:/config:z
      - ${SILVASONIC_DATA_DIR}/logs:/var/log/silvasonic:z
      - ${SILVASONIC_DATA_DIR}/status:/mnt/data/services/silvasonic/status:z

  db:
    image: docker.io/library/postgres:15-alpine
    container_name: silvasonic_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-silvasonic}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-silvasonic}
      POSTGRES_DB: ${POSTGRES_DB:-silvasonic}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ${SILVASONIC_DATA_DIR}/db/data:/var/lib/postgresql/data:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U silvasonic"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

    # --- Multi-Microphone Examples ---
    # To add a second microphone (e.g. Back):
    # 1. Duplicate the 'recorder' service block above.
    # 2. Rename it to 'recorder_back'.
    # 3. Set container_name: silvasonic_recorder_back
    # 4. Set environment:
    #      - AUDIO_PROFILE=back_mic  # Folder will be /data/recording/back_mic
    #      - LIVE_STREAM_PORT=1235   # Unique port
    # 5. Map correct device:
    #      - /dev/snd/pcmC2D0c:/dev/snd/pcmC2D0c

    #livesound:
    #  environment:
    #    - LISTEN_PORTS=front:1234,back:1235  # Map sources to ports
    #  ports:
    #    - "1235:1235/udp"  # Expose extra ports

    #uploader:
    #  environment:
    #    - SENSOR_ID=my_sensor_01  # Optional: Override hostname for cloud upload path
