version: "3.8"

# =============================================================================
# Silvasonic Sensor Stack
# =============================================================================
# Usage:
#   sudo podman-compose -f podman-compose.yml up --build -d
#   sudo podman-compose -f podman-compose.yml logs -f
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # Recorder (formerly Ear) - Primary Microphone
  # ---------------------------------------------------------------------------
  # Captures audio and stores it in /data/recording
  # ---------------------------------------------------------------------------
  recorder:
    build:
      context: containers/recorder
    image: silvasonic-recorder:latest
    container_name: silvasonic_recorder

    environment:
      - PYTHONUNBUFFERED=1

    devices:
      - /dev/snd:/dev/snd
    privileged: true

    volumes:
      # Master Audio Storage
      - /mnt/data/services/silvasonic/recorder/recordings:/data/recording:z
      # Shared Logs
      - /mnt/data/services/silvasonic/logs:/var/log/silvasonic:z
      # Shared Status
      - /mnt/data/services/silvasonic/status:/mnt/data/services/silvasonic/status:z

    restart: always

  # ---------------------------------------------------------------------------
  # Uploader (formerly Carrier) - Data Sync
  # ---------------------------------------------------------------------------
  # Syncs recordings to cloud (Rclone)
  # ---------------------------------------------------------------------------
  uploader:
    build:
      context: containers/uploader
    image: silvasonic-uploader:latest
    container_name: silvasonic_uploader
    hostname: silvasonic-uploader
    restart: always

    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000

    volumes:
      # Read-only access to recordings from Recorder
      - /mnt/data/services/silvasonic/recorder/recordings:/data/recording:ro
      # Rclone Config Persistence
      - /mnt/data/services/silvasonic/uploader/config:/config/rclone:z
      # Shared Logs
      - /mnt/data/services/silvasonic/logs:/var/log/silvasonic:z
      # Shared Status & Errors
      - /mnt/data/services/silvasonic/status:/mnt/data/services/silvasonic/status:z
      - /mnt/data/services/silvasonic/errors:/mnt/data/services/silvasonic/errors:z

  # ---------------------------------------------------------------------------
  # HealthChecker (formerly Notifier) - Alerts & Monitoring
  # ---------------------------------------------------------------------------
  healthchecker:
    build:
      context: containers/healthchecker
    image: silvasonic-healthchecker:latest
    container_name: silvasonic_healthchecker
    restart: always
    env_file: .env
    volumes:
      # Shared Status & Errors (Read/Write for archiving errors and writing own status)
      - /mnt/data/services/silvasonic/status:/mnt/data/services/silvasonic/status:z
      - /mnt/data/services/silvasonic/errors:/mnt/data/services/silvasonic/errors:z

  # ---------------------------------------------------------------------------
  # BirdNET - Species Identification
  # ---------------------------------------------------------------------------
  birdnet:
    build:
      context: containers/birdnet
    image: silvasonic-birdnet:latest
    container_name: silvasonic_birdnet

    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_DIR=/data/recording
      - DB_PATH=/data/db/birdnet.sqlite
      - RESULTS_DIR=/data/results
      - MIN_CONFIDENCE=0.7
      - RECURSIVE_WATCH=true

    volumes:
      # Read-only access to recordings
      - /mnt/data/services/silvasonic/recorder/recordings:/data/recording:ro
      # Isolated Results
      - /mnt/data/services/silvasonic/birdnet/results:/data/results:z
      # Shared Logs
      - /mnt/data/services/silvasonic/logs:/var/log/silvasonic:z
      # Shared Status
      - /mnt/data/services/silvasonic/status:/mnt/data/services/silvasonic/status:z

    restart: always

  # ---------------------------------------------------------------------------
  # SoundAnalyser (formerly Brain) - Edge Analysis
  # ---------------------------------------------------------------------------
  sound_analyser:
    build:
      context: containers/sound_analyser
    image: silvasonic-sound-analyser:latest
    container_name: silvasonic_sound_analyser

    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_DIR=/data/recording
      - DB_PATH=/data/db/brain.sqlite
      - RECURSIVE_WATCH=true

    # Low priority to prevent starvation of recorder/birdnet
    cpu_shares: 128
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M

    volumes:
      # Read-only access to recordings
      - /mnt/data/services/silvasonic/recorder/recordings:/data/recording:ro
      # Isolated DB (Legacy SQLite)
      - /mnt/data/services/silvasonic/sound_analyser/db:/data/db:z
      # Artifacts (Spectrograms etc)
      - /mnt/data/services/silvasonic/sound_analyser/artifacts:/data/processed/artifacts:z
      # Metadata (JSON Exports)
      - /mnt/data/services/silvasonic/sound_analyser/metadata:/data/processed/metadata:z
      # Shared Logs
      - /mnt/data/services/silvasonic/logs:/var/log/silvasonic:z
      # Shared Status
      - /mnt/data/services/silvasonic/status:/mnt/data/services/silvasonic/status:z

    restart: always

  # ---------------------------------------------------------------------------
  # Database (PostgreSQL) - Central Storage
  # ---------------------------------------------------------------------------
  db:
    image: docker.io/library/postgres:15-alpine
    container_name: silvasonic_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-silvasonic}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-silvasonic}
      POSTGRES_DB: ${POSTGRES_DB:-silvasonic}
    volumes:
      - /mnt/data/services/silvasonic/db/data:/var/lib/postgresql/data:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U silvasonic"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  # ---------------------------------------------------------------------------
  # Dashboard (The Face) - Status UI
  # ---------------------------------------------------------------------------
  dashboard:
    build:
      context: containers/dashboard
    image: silvasonic-dashboard:latest
    container_name: silvasonic_dashboard
    hostname: silvasonic-dashboard
    restart: always
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"
    volumes:
      # Read-Only Audio (Playback)
      - /mnt/data/services/silvasonic/recorder/recordings:/data/recording:ro
      # Shared Logs (View)
      - /mnt/data/services/silvasonic/logs:/var/log/silvasonic:ro
      # Shared Status
      - /mnt/data/services/silvasonic/status:/mnt/data/services/silvasonic/status:ro
      # Spectrograms from Brain
      - /mnt/data/services/silvasonic/sound_analyser/artifacts:/data/processed/artifacts:ro
      # System Stats (Optional, depends on host)
      # - /etc/localtime:/etc/localtime:ro
