version: "3.8"

services:
  tailscale:
    image: docker.io/tailscale/tailscale:latest
    container_name: silvasonic_tailscale
    hostname: ${HOSTNAME:-silvasonic-unit}
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_HOSTNAME=${HOSTNAME:-silvasonic-unit}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - tailscale_state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: always
    security_opt:
      - label=disable
    privileged: true

  gateway:
    image: docker.io/library/caddy:alpine
    container_name: silvasonic_gateway
    restart: always
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./containers/gateway/Caddyfile:/etc/caddy/Caddyfile:ro,z

  controller:
    build:
      context: containers/controller
    image: silvasonic-controller:latest
    container_name: silvasonic_controller
    privileged: true # To spawn privileged siblings and access Host hardware info
    environment:
      # Pass Host paths so Controller can map them into Child Recorders
      - HOST_SILVASONIC_DATA_DIR=${SILVASONIC_DATA_DIR}
      # - HOST_RECORDER_SRC=./containers/recorder/src  # Optional: For dev hot-reload in siblings
      - CONTAINER_HOST=unix:///run/podman/podman.sock # Force usage of mounted host socket
    volumes:
      # 1. Podman Socket (Orchestration)
      - ${PODMAN_SOCKET}:/run/podman/podman.sock:z
      # 2. Hardware Discovery
      - /dev:/dev:ro
      - /run/udev:/run/udev:ro
      # 3. Source Code (Deployment)
      - ${SILVASONIC_DATA_DIR}/config/profiles:/app/mic_profiles:ro
      # 4. Logs
      - ${SILVASONIC_DATA_DIR}/logs:/var/log/silvasonic:z
      # 5. Shared Status (Live Config)
    devices:
      - /dev/snd:/dev/snd
      - /dev/bus/usb:/dev/bus/usb
    group_add:
      - audio
      - plugdev
      - video
      - dialout
      - gpio
      - render
    restart: always


  uploader:
    build:
      context: containers/uploader
    image: silvasonic-uploader:latest
    container_name: silvasonic_uploader
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
      - POSTGRES_HOST=db
      - PYTHONPATH=/app/src
    volumes:
      - ./containers/uploader/src:/app/src:z
      - ${SILVASONIC_DATA_DIR}/recorder/recordings:/data/recording:ro
      - ${SILVASONIC_DATA_DIR}/uploader/config:/config/rclone:z
      - ${SILVASONIC_DATA_DIR}/logs:/var/log/silvasonic:z

      - ${SILVASONIC_DATA_DIR}/errors:/mnt/data/services/silvasonic/errors:z
    ports:
      - "8001:8001"
    restart: always

  healthchecker:
    build:
      context: containers/healthchecker
    image: silvasonic-healthchecker:latest
    container_name: silvasonic_healthchecker
    restart: always
    env_file: .env
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./containers/healthchecker/src:/app/src:z
      - ${SILVASONIC_DATA_DIR}/config:/config:z

      - ${SILVASONIC_DATA_DIR}/errors:/mnt/data/services/silvasonic/errors:z
      - ${SILVASONIC_DATA_DIR}/notifications:/data/notifications:z
      - ${SILVASONIC_DATA_DIR}/logs:/var/log/silvasonic:z



  birdnet:
    build:
      context: containers/birdnet
    image: silvasonic-birdnet:latest
    container_name: silvasonic_birdnet_template
    entrypoint: ["/bin/true"]
    restart: "no"
    volumes:
      - ./containers/birdnet/src:/app/src:z

  recorder:
    build:
      context: containers/recorder
    image: silvasonic-recorder:latest
    container_name: silvasonic_recorder_template
    # Template container: Stopped by default, used as image source or dev base
    entrypoint: ["/bin/true"]
    restart: "no"
    volumes:
      - ./containers/recorder/src:/app/src:z
      - ${SILVASONIC_DATA_DIR}/config/profiles:/app/mic_profiles:ro
      - ${SILVASONIC_DATA_DIR}/recorder/recordings:/data/recording:z
      - ${SILVASONIC_DATA_DIR}/logs:/var/log/silvasonic:z
      - /proc/asound:/proc/asound:ro

      - /sys:/sys:ro

  livesound:
    build:
      context: containers/livesound
    image: silvasonic-livesound:latest
    container_name: silvasonic_livesound
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8010:8010/udp"
    cpu_shares: 512
    volumes:
      - ./containers/livesound/src:/app/src:z
      - ${SILVASONIC_DATA_DIR}/recorder/recordings:/data/recording:ro
      - ${SILVASONIC_DATA_DIR}/logs:/var/log/silvasonic:z

    restart: always

  dashboard:
    build:
      context: containers/dashboard
    image: silvasonic-dashboard:latest
    container_name: silvasonic_dashboard
    hostname: silvasonic-dashboard
    restart: always
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    ports: []
    volumes:
      - ./containers/dashboard/src:/app/src:z
      - ${SILVASONIC_DATA_DIR}/recorder/recordings:/data/recording:ro
      - ${SILVASONIC_DATA_DIR}/config:/config:z
      - ${SILVASONIC_DATA_DIR}/config/profiles:/app/mic_profiles:z
      - ${SILVASONIC_DATA_DIR}/logs:/var/log/silvasonic:z




  weather:
    build:
      context: containers/weather
    image: silvasonic-weather:latest
    container_name: silvasonic_weather_template
    entrypoint: ["/bin/true"]
    restart: "no"
    volumes:
      - ./containers/weather/src:/app/src:z

  db:
    image: docker.io/library/postgres:15-alpine
    container_name: silvasonic_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-silvasonic}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-silvasonic}
      POSTGRES_DB: ${POSTGRES_DB:-silvasonic}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ${SILVASONIC_DATA_DIR}/db/data:/var/lib/postgresql/data:z
      - ./containers/db/init:/docker-entrypoint-initdb.d:z
      - ./containers/db/postgresql.conf:/etc/postgresql/postgresql.conf:z

      - ./containers/db/postgresql.conf:/etc/postgresql/postgresql.conf:z
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U silvasonic"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: silvasonic_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ${SILVASONIC_DATA_DIR}/redis/data:/data:z
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

    # --- Multi-Microphone Examples ---
    # To add a second microphone (e.g. Back):
    # 1. Duplicate the 'recorder' service block above.
    # 2. Rename it to 'recorder_back'.
    # 3. Set container_name: silvasonic_recorder_back
    # 4. Set environment:
    #      - AUDIO_PROFILE=back_mic  # Folder will be /data/recording/back_mic
    #      - LIVE_STREAM_PORT=1235   # Unique port
    # 5. Map correct device & Discovery paths:
    #      - /dev/snd/pcmC2D0c:/dev/snd/pcmC2D0c
    #      - /proc/asound:/proc/asound:ro
    #      - /sys:/sys:ro

    #livesound:
    #  environment:
    #    - LISTEN_PORTS=front:1234,back:1235  # Map sources to ports
    #  ports:
    #    - "1235:1235/udp"  # Expose extra ports

    #  environment:
    #    - SENSOR_ID=my_sensor_01  # Optional: Override hostname for cloud upload path

volumes:
  tailscale_state:

