import json
import time
import typing

import redis

from .common import logger


class HealthCheckerService:
    @staticmethod
    def get_status() -> dict[str, typing.Any]:
        try:
            r = redis.Redis(host="silvasonic_redis", port=6379, db=0, socket_connect_timeout=1)
            content = r.get("status:healthchecker")
            if content:
                data = json.loads(content)
                # Check freshness
                if time.time() - data.get("timestamp", 0) > 120:
                    data["status"] = "Stalled"
                return typing.cast(dict[str, typing.Any], data)
        except Exception as e:
            logger.error(f"HealthChecker status error: {e}", exc_info=True)

        return {"status": "Unknown"}

    @staticmethod
    def get_system_metrics() -> dict[str, typing.Any]:
        """Reads the consolidated system status from Redis (generated by HealthChecker)."""
        try:
            r = redis.Redis(host="silvasonic_redis", port=6379, db=0, socket_connect_timeout=1)
            content = r.get("system:status")
            if content:
                return typing.cast(dict[str, typing.Any], json.loads(content))

        except Exception as e:
            logger.error(f"System metrics error: {e}", exc_info=True)

        return {}
